### ISSUE TITLE
dataPoints array prop watcher should be structured with a `deep` option 

### ISSUE THREAD

**Issue by cagonzalezcs** [lafriks/vue-bar-graph#19]
Hello @lafriks, thanks for forking this project and updating it to be compatible with Vue 3. 

I found an issue when attempting to resolve Vue 3 migration errors within my own project in relation to this package. It appears that the watcher used to act upon changes of the `VueBarGraph.dataPoints` prop needs to pass an option of `deep: true` in order to function as expected.

https://v3-migration.vuejs.org/breaking-changes/watch.html

I have a patch here that could resolve the issue, but I'm unsure if anything else would be required.

Relevant PR - https://github.com/lafriks/vue-bar-graph/pull/20

Would it be possible to resolve this issue?

**Comment by lafriks** [comment]
@cagonzalezcs [v2.2.0](https://www.npmjs.com/package/vue-bar-graph/v/2.2.0) published
