### ISSUE TITLE
Set bar color

### ISSUE THREAD

**Issue by nikzanda** [lafriks/vue-bar-graph#2]
It would be nice to be able to set color bars.

For this purpose, I'm using JavaScript like this:

```
let rects = document.getElementsByTagName("rect");
rects.forEach((rect) => {
    rect.style.fill = "#ffff00";
});
```

In this way it works! But it would be nicer to be able to pass a color array to the component.

**Comment by lafriks** [comment]
Fixed in 1.3.0, see sample: https://github.com/lafriks/vue-bar-graph/blob/master/src/App.vue#L175
