### ISSUE TITLE
Lables are not shown

### ISSUE THREAD

**Issue by dragon74** [lafriks/vue-bar-graph#5]
Definition:
<vue-bar-graph  :points="points"
                  :width="400"
                  :height="200"
                  :show-x-axis="true"
                  :show-values="true"
                  :use-custom-labels="true"                 
                />

And for example points are: [{label: 'AA', value: 0},{label: 'BB', value: 0}]
Also tries adding the lables through the lables attribute...

**Comment by lafriks** [comment]
you need to provide `:use-custom-labels="true"` attribute for this to work

**Comment by lafriks** [comment]
If it does not work please provide more complete example and reopen issue
