### ISSUE TITLE
Labels are not show, cont.

### ISSUE THREAD

**Issue by dragon74** [lafriks/vue-bar-graph#6]
Definition:
vue-bar-graph  :points="points"
                  :width="400"
                  :height="200"
                  :show-x-axis="true"
                  :show-values="true"
                  :use-custom-labels="true"                 

And for example points are: [{label: 'AA', value: 0},{label: 'BB', value: 0}]
Also tries adding the lables through the lables attribute...
Note that I DO use 'use custom labels'
Please do not close this, as this is urgent...if you need more info I shall provide it

**Comment by lafriks** [comment]
Sorry, I misunderstood what you want, you don't need `:use-custom-labels="true"`:
```vue
    <vue-bar-graph
      :points="points"
      :width="400"
      :height="200"
      :show-x-axis="true"
      :show-values="true"
    />
```

Seems to be working just fine:
![attels](https://user-images.githubusercontent.com/165205/118109656-263a3480-b3ea-11eb-889f-f15b21a98d08.png)

**Comment by dragon74** [comment]
Works great! Thanksss!
