### ISSUE TITLE
How can I give each bar a different color?

### ISSUE THREAD

**Issue by dragon74** [lafriks/vue-bar-graph#7]

**Comment by lafriks** [comment]
see example here: https://github.com/lafriks/vue-bar-graph/blob/master/src/App.vue#L176

**Comment by dragon74** [comment]
Thanks for the quick reply!
I defined the points like this, but the bars are still blue...

let res = [{label: lbl1, value: 10, barColor: '#00ff00', textColor: '#00ffff', textAltColor: '#0000ff'},
                   {label: lbl2, value: 20, barColor: '#ff0000',textColor: '#00ffff', textAltColor: '#0000ff'}]

 <vue-bar-graph v-show="showGraph"
                    :points="points"
                    :width="1000"
                    :height="500"                  
                    :show-x-axis="true"
                    :show-values="true" 
                    :text-font="50" 
                    :label-height="52"                                     
                  />

**Comment by lafriks** [comment]
do you use latest 1.3.0 version?

**Comment by dragon74** [comment]
Updated to 1.3 and the colors worked, thanks a lot!!!
One last thing - the label height does not affect, and I get the attached
result with this def (played with the height but no effect)

  <vue-bar-graph v-show="showGraph"
                    :points="points"
                    :width="1000"
                    :height="500"
                    :show-x-axis="true"
                    :show-values="true"
                    :text-font="'40px sans-serif'"
                    :label-height="100"
                  />
                </div>

**Comment by lafriks** [comment]
try:
```
 :text-font="'sans-serif 40px'"
 ```

**Comment by dragon74** [comment]
Then the font is smaller (I guess the default is taken)

Thanks<
Danny
