### ISSUE TITLE
How can I change the font size of the labels?

### ISSUE THREAD

**Issue by dragon74** [lafriks/vue-bar-graph#8]

**Comment by lafriks** [comment]
Use `text-font="font <size>px"` together with `:label-height="<size+2>"`:
https://github.com/lafriks/vue-bar-graph/blob/master/src/components/VueBarGraph.vue#L147
https://github.com/lafriks/vue-bar-graph/blob/master/src/components/VueBarGraph.vue#L136

**Comment by dragon74** [comment]
label-height does not affect :(
I tried with font size 40 and it overlappes the bars
